name: Create Release on Tags

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - '**'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tag detected = ${{ github.ref }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Get project version with Maven
        run: |
          project_version=$(mvn help:evaluate -q -Dexpression=project.version -DforceStdout=true)
          echo "Project version fetched = $project_version"
          echo "project_version=$project_version" >> $GITHUB_ENV
      - name: Test var accessible in next step
        run: echo "Project Version is ${{ env.project_version }}"
